language: rust
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    -
    - RELEASE=true

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

script:
  - make test doc bench
  - make longtest
